const OPERATIONS = {
    /* Achievement category operations */

    ACHIEVEMENT_CATEGORY_CREATE: 1,
    ACHIEVEMENT_CATEGORY_UPDATE: 2,
    ACHIEVEMENT_CATEGORY_DELETE: 3,
    ACHIEVEMENT_CATEGORY_LIST: 4,
    ACHIEVEMENT_CATEGORY_MANAGE: 5,

    /* Achievement operations */

    ACHIEVEMENT_CREATE: 6,
    ACHIEVEMENT_UPDATE: 7,
    ACHIEVEMENT_DELETE: 8,
    ACHIEVEMENT_LIST: 9,
    ACHIEVEMENT_MANAGE: 10,

    /* Algorithm category operations */

    ALGORITHM_CATEGORY_CREATE: 11,
    ALGORITHM_CATEGORY_UPDATE: 12,
    ALGORITHM_CATEGORY_DELETE: 13,
    ALGORITHM_CATEGORY_LIST: 14,
    ALGORITHM_CATEGORY_MANAGE: 15,

    /* Algorithm complexity operations */

    ALGORITHM_COMPLEXITY_CREATE: 16,
    ALGORITHM_COMPLEXITY_UPDATE: 17,
    ALGORITHM_COMPLEXITY_DELETE: 18,
    ALGORITHM_COMPLEXITY_LIST: 19,
    ALGORITHM_COMPLEXITY_MANAGE: 20,

    /* Algorithm difficulty level operations */

    ALGORITHM_DIFFICULTY_LEVEL_CREATE: 21,
    ALGORITHM_DIFFICULTY_LEVEL_UPDATE: 22,
    ALGORITHM_DIFFICULTY_LEVEL_DELETE: 23,
    ALGORITHM_DIFFICULTY_LEVEL_LIST: 24,
    ALGORITHM_DIFFICULTY_LEVEL_MANAGE: 25,

    /* Algorithm implementation operations */

    ALGORITHM_IMPLEMENTATION_CREATE: 26,
    ALGORITHM_IMPLEMENTATION_UPDATE: 27,
    ALGORITHM_IMPLEMENTATION_DELETE: 28,
    ALGORITHM_IMPLEMENTATION_LIST: 29,
    ALGORITHM_IMPLEMENTATION_MANAGE: 30,

    /* Algorithm operations */

    ALGORITHM_CREATE: 31,
    ALGORITHM_UPDATE: 32,
    ALGORITHM_DELETE: 33,
    ALGORITHM_LIST: 34,
    ALGORITHM_MANAGE: 35,

    /* Code language operations */

    CODE_LANGUAGE_CREATE: 36,
    CODE_LANGUAGE_UPDATE: 37,
    CODE_LANGUAGE_DELETE: 38,
    CODE_LANGUAGE_LIST: 39,
    CODE_LANGUAGE_MANAGE: 40,

    /* Feedback operations */

    FEEDBACK_CREATE: 41,
    FEEDBACK_UPDATE: 42,
    FEEDBACK_DELETE: 43,
    FEEDBACK_LIST: 44,
    FEEDBACK_MANAGE: 45,

    /* Input based task operations */

    INPUT_BASED_TASK_CREATE: 46,
    INPUT_BASED_TASK_UPDATE: 47,
    INPUT_BASED_TASK_DELETE: 48,
    INPUT_BASED_TASK_LIST: 49,
    INPUT_BASED_TASK_MANAGE: 50,

    /* Lesson operations */

    LESSON_CREATE: 51,
    LESSON_UPDATE: 52,
    LESSON_DELETE: 53,
    LESSON_LIST: 54,
    LESSON_MANAGE: 55,

    /* Module operations */

    MODULE_CREATE: 56,
    MODULE_UPDATE: 57,
    MODULE_DELETE: 58,
    MODULE_LIST: 59,
    MODULE_MANAGE: 60,

    /* Multimedia operations */

    MULTIMEDIA_CREATE: 61,
    MULTIMEDIA_UPDATE: 62,
    MULTIMEDIA_DELETE: 63,
    MULTIMEDIA_LIST: 64,
    MULTIMEDIA_MANAGE: 65,

    /* Multimedia category operations */

    MULTIMEDIA_CATEGORY_CREATE: 66,
    MULTIMEDIA_CATEGORY_UPDATE: 67,
    MULTIMEDIA_CATEGORY_DELETE: 68,
    MULTIMEDIA_CATEGORY_LIST: 69,
    MULTIMEDIA_CATEGORY_MANAGE: 70,

    /* Operation operations */

    OPERATION_CREATE: 71,
    OPERATION_UPDATE: 72,
    OPERATION_DELETE: 73,
    OPERATION_LIST: 74,
    OPERATION_MANAGE: 75,

    /* Permission operations */

    PERMISSION_CREATE: 76,
    PERMISSION_UPDATE: 77,
    PERMISSION_DELETE: 78,
    PERMISSION_LIST: 79,
    PERMISSION_MANAGE: 80,

    /* Role operations */

    ROLE_CREATE: 81,
    ROLE_UPDATE: 82,
    ROLE_DELETE: 83,
    ROLE_LIST: 84,
    ROLE_MANAGE: 85,

    /* Select based task operations */

    SELECT_BASED_TASK_CREATE: 86,
    SELECT_BASED_TASK_UPDATE: 87,
    SELECT_BASED_TASK_DELETE: 88,
    SELECT_BASED_TASK_LIST: 89,
    SELECT_BASED_TASK_MANAGE: 90,

    /* Sort based task operations */

    SORT_BASED_TASK_CREATE: 91,
    SORT_BASED_TASK_UPDATE: 92,
    SORT_BASED_TASK_DELETE: 93,
    SORT_BASED_TASK_LIST: 94,
    SORT_BASED_TASK_MANAGE: 95,

    /* Task difficulty level operations */

    TASK_DIFFICULTY_LEVEL_CREATE: 96,
    TASK_DIFFICULTY_LEVEL_UPDATE: 97,
    TASK_DIFFICULTY_LEVEL_DELETE: 98,
    TASK_DIFFICULTY_LEVEL_LIST: 99,
    TASK_DIFFICULTY_LEVEL_MANAGE: 100,

    /* Task type operations */

    TASK_TYPE_CREATE: 101,
    TASK_TYPE_UPDATE: 102,
    TASK_TYPE_DELETE: 103,
    TASK_TYPE_LIST: 104,
    TASK_TYPE_MANAGE: 105,

    /* Task operations */

    TASK_CREATE: 106,
    TASK_UPDATE: 107,
    TASK_DELETE: 108,
    TASK_LIST: 109,
    TASK_MANAGE: 110,

    /* Time unit operations */

    TIME_UNIT_CREATE: 111,
    TIME_UNIT_UPDATE: 112,
    TIME_UNIT_DELETE: 113,
    TIME_UNIT_LIST: 114,
    TIME_UNIT_MANAGE: 115,

    /* User operations */

    USER_CREATE: 116,
    USER_UPDATE: 117,
    USER_DELETE: 118,
    USER_LIST: 119,
    USER_MANAGE: 120,

    /* Visualization operations */

    VISUALIZATION_CREATE: 121,
    VISUALIZATION_UPDATE: 122,
    VISUALIZATION_DELETE: 123,
    VISUALIZATION_LIST: 124,
    VISUALIZATION_MANAGE: 125,
};

module.exports = OPERATIONS;